covid-testing-managagement-system/covid-testing-managagement-system/Controllers/SymtomCheckerController.cs
using covid_testing_managagement_system.Interfaces;
using covid_testing_managagement_system.Models;
using covid_testing_managagement_system.Models.Admin;
using covid_testing_managagement_system.Models.Infermedica.Request;
using covid_testing_managagement_system.Models.Infermedica.Response;
using covid_testing_managagement_system.RepositoryInterfaces;
using covid_testing_managagement_system.Services;
using covid_testing_managagement_system.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static covid_testing_managagement_system.Models.Infermedica.Response.Question;

namespace covid_testing_managagement_system.Controllers
{
    public class SymtomCheckerController : Controller
    {

        private readonly string TRIAGE_MODEL_KEY = "_TriageViewModelData";
        private readonly ILogger<SymtomCheckerController> _logger;
        private readonly IInfermedicaService _infermedicaService;
        private readonly IPatientRepository _patientRepository;
        private readonly IInterviewRepository _interviewRepository;
        private readonly IInterviewEvidenceRepository _interviewEvidenceRepository;

        public SymtomCheckerController(ILogger<SymtomCheckerController> logger, IInfermedicaService infermedicaService, IPatientRepository patientRepository, IInterviewRepository interviewRepository, IInterviewEvidenceRepository interviewEvidenceRepository)
        {
            _infermedicaService = infermedicaService;
            _logger = logger;
            _patientRepository = patientRepository;
            _interviewRepository = interviewRepository;
            _interviewEvidenceRepository = interviewEvidenceRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PatientInfo()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PatientInfo(SymtomCheckerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            model.Response = await _infermedicaService.SendDiagnosisRequestAsync(model.Request);
            if (model.Response.ShouldStop)
            {
                HttpContext.Session.Set<InfermedicaRequest>(TRIAGE_MODEL_KEY, model.Request);
                return RedirectToAction(nameof(Results));
            }

            if (model.Response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                return StatusCode((int)model.Response.StatusCode);
            }

            string id = model.Response.Question.Items[0].Id;
            HttpContext.Session.Set(id, model);
            return RedirectToAction(nameof(Symtoms), new { Q_ID = id });
        }

        public ActionResult Symtoms(string Q_ID)
        {
            SymtomCheckerViewModel model = HttpContext.Session.Get<SymtomCheckerViewModel>(Q_ID);
            if (!ModelState.IsValid)
            {
                return View(nameof(Symtoms), model);
            }

            if (model == null)
            {
                _logger.LogError("No session data found for SymtomCheckerViewModel");
                return StatusCode(500);
            }

            string id = model.Response.Question.Items[0].Id;
            HttpContext.Session.Set(id, model);
            return View(nameof(Symtoms), model.Response.Question);
        }

        [HttpPost]
        public async Task<ActionResult> Symtoms(Question question)
        {
            SymtomCheckerViewModel model = HttpContext.Session.Get<SymtomCheckerViewModel>(question.Items[0].Id);
            if (!ModelState.IsValid)
            {
                return View(nameof(Symtoms), model);
            }

            if (model == null)
            {
                _logger.LogError("No session data found for SymtomCheckerViewModel");
                return StatusCode(500);
            }

            if (question.Type != QuestionType.group_single)
            {
                foreach (Item item in question.Items)
                {
                    Models.Infermedica.Request.Evidence evidence = new Models.Infermedica.Request.Evidence
                    {
                        Id = item.Id
                    };
                    evidence.ChoiceId = item.Choice ? Models.Infermedica.Choice.present : Models.Infermedica.Choice.absent;
                    model.Request.AddEvidence(evidence);
                }
            }
            else
            {
                foreach (Item item in question.Items)
                {
                    if (item.Choice)
                    {
                        Models.Infermedica.Request.Evidence evidence = new Models.Infermedica.Request.Evidence
                        {
                            Id = item.Id
                        };
                        evidence.ChoiceId = item.Choice ? Models.Infermedica.Choice.present : Models.Infermedica.Choice.absent;
                        model.Request.AddEvidence(evidence);
                        break;
                    }
                }
            }

            model.Response = await _infermedicaService.SendDiagnosisRequestAsync(model.Request);
            if (model.Response.ShouldStop)
            {
                TriageViewModel triageViewModel = new TriageViewModel
                {
                    Request = model.Request
                };
                HttpContext.Session.Set(TRIAGE_MODEL_KEY, triageViewModel);
                return RedirectToAction(nameof(Results));
            }

            if (model.Response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                return StatusCode((int)model.Response.StatusCode);
            }

            string id = model.Response.Question.Items[0].Id;
            HttpContext.Session.Set(id, model);
            return RedirectToAction(nameof(Symtoms), new { Q_ID = id });
        }

        public async Task<ActionResult> Results()
        {
            TriageViewModel triageViewModel = HttpContext.Session.Get<TriageViewModel>(TRIAGE_MODEL_KEY);
            if (triageViewModel == null)
            {
                _logger.LogWarning("Page was called with no triageViewModel view data");
                return BadRequest();
            }

            triageViewModel.Response = await _infermedicaService.SendTriageRequestAsync(triageViewModel.Request);

            if (triageViewModel.Response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                return StatusCode((int)triageViewModel.Response.StatusCode);
            }

            HttpContext.Session.Set(TRIAGE_MODEL_KEY, triageViewModel);
            return View(triageViewModel.Response);
        }

        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ApplyAsync(PatientViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            TriageViewModel triageViewModel = HttpContext.Session.Get<TriageViewModel>(TRIAGE_MODEL_KEY);
            if (triageViewModel == null)
            {
                _logger.LogWarning("Page was called with no triageViewModel view data");
                return BadRequest();
            }

            if (triageViewModel.Request == null)
            {
                _logger.LogWarning("Page was called with no Triage Request data");
                return BadRequest();
            }

            if (triageViewModel.Response == null)
            {
                _logger.LogWarning("Page was called with no Triage Response data");
                return BadRequest();
            }

            Patient patient = new Patient
            {
                Age = triageViewModel.Request.Age,
                DateApplied = DateTime.Now,
                Email = model.Email,
                FirstName = model.FirstName,
                IdNumber = model.IdNumber,
                LastName = model.LastName
            };
            if (triageViewModel.Request.Sex == InfermedicaRequest.Gender.male)
            {
                patient.Sex = true;
            }
            else
            {
                patient.Sex = false;
            }

            patient = await _patientRepository.AddPatientAsync(patient);
            int interviewId = await _interviewRepository.AddInterviewAsync(patient.Id);
            IEnumerable<InterviewEvidence> interviewEvidence = ConvertEvidence(interviewId, triageViewModel.Request.Evidence);
            await _interviewEvidenceRepository.AddInterviewEvidenceAsync(interviewEvidence);

            return RedirectToAction(nameof(Applied));
        }

        private IEnumerable<InterviewEvidence> ConvertEvidence(int interviewId, List<Models.Infermedica.Request.Evidence> evidence)
        {
            return evidence.Select(e => new InterviewEvidence { InterviewId = interviewId, ApiId = e.Id, Choice = e.ChoiceId == Models.Infermedica.Choice.present });
        }

        public IActionResult Applied()
        {
            return View();
        }
    }
}

covid-testing-managagement-system/covid-testing-managagement-system/Views/Shared/_Layout.cshtml
@* TODO: Need to inject login state here or have another layout *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Covid-19 Symptom Checker</title>
    <link rel="icon" href="~/favicon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @* <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"> *@
    @RenderSection("Styles", false)
</head>
<body>
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom">
            <div class="container-fluid d-flex justify-content-between">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img id="logo" src="~/Img/logo@2x.png"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SymtomChecker" asp-action="Index">Symtom Checker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Signup">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@

    <div class="d-flex">

        @* <aside id="sidebar" class="sidebar shadow-lg">

        </aside> *@

        <main role="main" class="container-fluid px-0 pb-0">
            @RenderBody()
        </main>

    </div>
    @*<div class="spacer"></div>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

covid-testing-managagement-system/covid-testing-managagement-system/Views/Shared/_NavBarPartial.cshtml
<nav class="navbar navbar-white">
    <a class="navbar-brand nav-logo-pos" asp-area="" asp-controller="Home" asp-action="Index">
        <img src="~/Img/logo@2x.png" style="width:8rem;" class="logo" />
    </a>
</nav>